import type { SchemePreset } from "@/types/calculator"

export const SCHEME_PRESETS: SchemePreset[] = [
  {
    id: "micro-credit",
    nameKey: "calculator.presetMicroCredit",
    defaultName: {
      en: "Micro Credit Scheme",
      hi: "माइक्रो क्रेडिट योजना",
    },
    principal: 120000,
    annualRatePct: 5.0,
    tenureMonths: 36,
    moratoriumMonths: 3,
    moratoriumInterestAccrues: false,
    badge: "5.0% p.a.",
    category: "micro",
  },
  {
    id: "mahila-samriddhi",
    nameKey: "calculator.presetMahilaSamriddhi",
    defaultName: {
      en: "Mahila Samriddhi Yojana",
      hi: "महिला समृद्धि योजना",
    },
    principal: 140000,
    annualRatePct: 4.0,
    tenureMonths: 36,
    moratoriumMonths: 3,
    moratoriumInterestAccrues: false,
    badge: "4.0% p.a.",
    category: "women",
  },
  {
    id: "term-loan",
    nameKey: "calculator.presetTermLoan",
    defaultName: {
      en: "Term Loan Scheme",
      hi: "टर्म लोन योजना",
    },
    principal: 500000,
    annualRatePct: 6.0,
    tenureMonths: 60,
    moratoriumMonths: 6,
    moratoriumInterestAccrues: false,
    badge: "6.0% p.a.",
    category: "term",
  },
  {
    id: "education-loan",
    nameKey: "calculator.presetEducationLoan",
    defaultName: {
      en: "Education Loan Scheme",
      hi: "शिक्षा ऋण योजना",
    },
    principal: 400000,
    annualRatePct: 4.0,
    tenureMonths: 60,
    moratoriumMonths: 12,
    moratoriumInterestAccrues: false,
    badge: "4.0% p.a.",
    category: "education",
  },
  {
    id: "commercial-bank",
    nameKey: "calculator.presetCommercialBank",
    defaultName: {
      en: "Commercial Bank (Ref)",
      hi: "वाणिज्यिक बैंक (तुलना)",
    },
    principal: 500000,
    annualRatePct: 10.5,
    tenureMonths: 60,
    moratoriumMonths: 0,
    moratoriumInterestAccrues: false,
    badge: "10.5% p.a.",
    category: "commercial",
  },
]
